stages:
  - build
  - deploy
cache:
  paths:
    - node_modules/
    - website/node_modules/

build-docs:
  image: node:12
  stage: build
  before_script:
    - cd website
    - yarn
  script:
    - yarn run build
    - mv build ../build
  artifacts:
    paths:
      - build/

pages:
  image: alpine:3.9
  stage: deploy
  dependencies:
    - build-docs
  script:
    - mv build/coding-standards public
  artifacts:
    paths:
      - public
  only:
    - master
